travis:
  secure:
    BINSTAR_TOKEN: VV5YcFIsKGPFJKeoH739m+C4l35kDx+qvVphWVG9eyLRkGJMqiztclCyEl+l8UximWq7nxoDrjLG+wOF59abv2ymYR0Xs2ee6oT0dKM0Hv1KjewarZbGOzHS+84XdSampRp7kpX+3Iw0IaBMLSfu2NSo2+zyjdzONO3FMaOp/Mg4DESeNXcjRYu/UT5z2DouJLXHs7KDZWcJjBSgSg2y4kc8WAmKHO1pxJjCXlgMDrG+TBmVmH/l4II4srAFD/jAYNWANsDC2FTZKNdM8gCE92LsGK81XLbAOOJ07do6Ai0IQqnMf+5gMk4tvpmzp9e+YQbsRoIjIe0wqIF/eIXOrVGjEFYH0+YQevucpIHV770tcL+LRSYFnDnOyjK/AdDo7hEBpktx2SOMpsGEt9sDprOiKYM8cKNjC+ice/G1nSUKJ47mppqCzgarrCNWc4/PHdbLWCxwbPqSBE4dH4BNyGsuwAE3cdzNrrx1xZzhISkON3tK9vout5dyzmE6JVelhMvj+k6wMfFs1CK/VhCRBJyXI75zPD6onx0vvMNHoSZOsQs06z5KqL/AlK9TEe/DnZT+6dRQqPeiqOQq/zmNN1rMndfSoA8snT5jopHUZ0VXQyaJf9jza7cKLehMewHV088BVbWk2ke9+HfJXNnXtaq4IWYTOX3ZfsiBEMkfPQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
